// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoMv9PB7gXQ-ZWFMIq-sG8_20YiWFVewk',
    appId: '1:42508636306:web:b0e3c3ac2133336765164b',
    messagingSenderId: '42508636306',
    projectId: 'linguaverse-db-il',
    authDomain: 'linguaverse-db-il.firebaseapp.com',
    storageBucket: 'linguaverse-db-il.firebasestorage.app',
    measurementId: 'G-RCKN4C538L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7YJMJFsjLULSwUa-6RNtrikawj5ueEG8',
    appId: '1:42508636306:android:217a077af7d3f23c65164b',
    messagingSenderId: '42508636306',
    projectId: 'linguaverse-db-il',
    storageBucket: 'linguaverse-db-il.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPd8KSsozCo7pVTK10hk3b2VUhgMLQcsw',
    appId: '1:42508636306:ios:922f54eb2612319465164b',
    messagingSenderId: '42508636306',
    projectId: 'linguaverse-db-il',
    storageBucket: 'linguaverse-db-il.firebasestorage.app',
    iosBundleId: 'com.ensias.linguaverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPd8KSsozCo7pVTK10hk3b2VUhgMLQcsw',
    appId: '1:42508636306:ios:922f54eb2612319465164b',
    messagingSenderId: '42508636306',
    projectId: 'linguaverse-db-il',
    storageBucket: 'linguaverse-db-il.firebasestorage.app',
    iosBundleId: 'com.ensias.linguaverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoMv9PB7gXQ-ZWFMIq-sG8_20YiWFVewk',
    appId: '1:42508636306:web:0bc6ed985299038065164b',
    messagingSenderId: '42508636306',
    projectId: 'linguaverse-db-il',
    authDomain: 'linguaverse-db-il.firebaseapp.com',
    storageBucket: 'linguaverse-db-il.firebasestorage.app',
    measurementId: 'G-6VTM4NCWZD',
  );
}
